//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwmasm
{


    public partial class adminDashboard
    {
        protected global::System.Web.UI.WebControls.Literal litUsersTotal;
        protected global::System.Web.UI.WebControls.Literal litProductsTotal;
        protected global::System.Web.UI.WebControls.Literal litOrdersTotal;
        protected global::System.Web.UI.WebControls.Literal litSalesTotal;
        protected global::System.Web.UI.WebControls.HiddenField hfChartData;
        protected global::System.Web.UI.WebControls.Repeater rptTopProducts;
    }
}
